name: EC2 Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - "ec2/**"

jobs:
  terraform-deploy:
    name: EC2 Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: ./ec2
        run: terraform init

      - name: Terraform Apply
        working-directory: ./ec2
        run: terraform apply -auto-approve
