name: EC2 Terraform CI

on:
  pull_request:
    paths:
      - "ec2/**"
    branches:
      - main

jobs:
  terraform-check:
    name: EC2 Terraform Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: ./ec2
        run: terraform init

      - name: Terraform Format
        working-directory: ./ec2
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./ec2
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./ec2
        run: terraform plan
