name: EC2 Terraform Workflow

on:
  pull_request:
    paths:
      - "ec2/**"
  push:
    paths:
      - "ec2/**"
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform Init
        working-directory: ec2
        run: terraform init

      - name: Terraform Format
        working-directory: ec2
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ec2
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: ec2
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ec2
        run: terraform apply -auto-approve
