# .github/workflows/tag-and-release.yml
name: Tag and Release

on:
  push:
    branches: [main]

permissions:
  contents: write # Required to create tags and releases

jobs:
  tag:
    name: Create SemVer Tag and Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We need to fetch all history and tags to correctly calculate the next version
          fetch-depth: 0 

      - name: Bump version and push tag
        id: tag_version
        uses: anothrNick/github-tag-action@1.67.0 # Use a specific version for stability
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true              # Puts a "v" in front of the tag (e.g., v1.0.0)
          DEFAULT_BUMP: "patch"     # If no conventional commit is found, default to a patch bump
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        if: ${{ steps.tag_version.outputs.new_tag }} # Only run if a new tag was created
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: false
          prerelease: false